### ISSUE TITLE
Move the API version slug to each call definition, instead of the base URL .

### ISSUE THREAD

**Issue by TheIronMarx** [MoonWolf125/2017MyriadMobileInternshipChallenge#1]
https://github.com/MoonWolf125/2017MyriadMobileInternshipChallenge/blob/fc41dc4e22247efdb2014084ac57bbc419790a89/dahnkyFinal/app/src/main/java/com/example/kl7304qk/dahnkyfinal/API/ApiService.java#L31

Some APIs will include a version slug. This is so that there may be a change or subtraction to a data type in their response object. Say if an endpoint changed a `String` value to a `double`, your app would likely break in production. Therefore, a new call is introduced, a `/v2/` replacing the `/v1/`, in a respective call, so that the app may be updated to support the breaking change, but existing versions will be unaffected. 

The issue lies in having your API call version in your base URL as seen above. This means you wouldn't be able to update one call without updating the rest of them. The non-updated calls would likely return a 404. 

I propose you move the `/v1/` suffix in the `baseUrl` to each individual `@GET()` annotation for your API call definitions.

**Comment by MoonWolf125** [comment]
I was not aware that allocating the version to the base URL could have that impact. I'll change this!
