### ISSUE TITLE
What's the reason for this warning suppression?

### ISSUE THREAD

**Issue by TheIronMarx** [MoonWolf125/2017MyriadMobileInternshipChallenge#3]
https://github.com/MoonWolf125/2017MyriadMobileInternshipChallenge/blob/fc41dc4e22247efdb2014084ac57bbc419790a89/dahnkyFinal/app/src/main/java/com/example/kl7304qk/dahnkyfinal/API/ApiService.java#L21

I fear it may block us from legitimate future problems.

**Comment by MoonWolf125** [comment]
That must have been a mistake when I was taking care of code inspections. I'll take care of that. Thanks!
