### ISSUE TITLE
Ah! The dreaded email regex!

### ISSUE THREAD

**Issue by TheIronMarx** [MoonWolf125/2017MyriadMobileInternshipChallenge#4]
https://github.com/MoonWolf125/2017MyriadMobileInternshipChallenge/blob/fc41dc4e22247efdb2014084ac57bbc419790a89/dahnkyFinal/app/src/main/java/com/example/kl7304qk/dahnkyfinal/activity/LoginActivity.java#L43

Validating emails is a classically difficult problem. I'm sure where ever you found that, there was text nearby saying how it wasn't perfect. Indeed it isn't.

The best way of validating emails is by sending a confirmation link via given email address. Of course, that is a good deal more work.

I offer two alternatives that will alleviate some frustration for your future users with goofy email addresses.

1. Use Android's own built in validator. It's more robust and comprehensive than an unreadable regex pattern that has been tweaked and copied and pasted throughout the internet for the last two decades. It can be done with `android.util.Patterns.EMAIL_ADDRESS.matcher("email@jeemail.cawm").matches()`

2. Don't validate emails at all. Maybe have them enter it twice and ensure they are the same, but there's just plenty of room to go wrong with valid email addresses that validation just isn't worth the time and hassle.

**Comment by MoonWolf125** [comment]
While looking at regexs I did come across some other solutions, none of them was the Android validator. I'll swap the regex out with that. I did come across email validation while looking for solutions and will remember it!
