### ISSUE TITLE
Where possible, prefer localized Contexts

### ISSUE THREAD

**Issue by TheIronMarx** [MoonWolf125/2017MyriadMobileInternshipChallenge#5]
https://github.com/MoonWolf125/2017MyriadMobileInternshipChallenge/blob/fc41dc4e22247efdb2014084ac57bbc419790a89/dahnkyFinal/app/src/main/java/com/example/kl7304qk/dahnkyfinal/activity/MainActivity.java#L56

In this case, we're using `getApplicationContext()` to get the `Context` that will set the adapter. In this case, that is completely valid and will likely never not work. However, there are some cases where you will need a more specific, localized `Context`. In this case, `Activity`'s `Context`. And what joy! An `Activity` _is_ a `Context`. We can simply pass in `this` as `Context` parameter because we're working within an `Activity`.

In general, aim to use the relevant `Activity`'s context.

**Comment by MoonWolf125** [comment]
Noted! I am aware of passing activities as contexts. I think I overlooked that a couple of times in this project.
